# Introduction

In this project, we will explore the most basic form of text classification. Text classification is a fundamental task in Natural Language Processing (NLP) where the goal is to assign predefined categories to text data.

To begin, I have downloaded several datasets from Kaggle. These datasets will be merged into a single unified dataset to ensure consistency and better training performance. After merging, we will perform data preprocessing, which may include cleaning the text, removing noise, handling missing values, and preparing the data for modeling.

Once the dataset is properly prepared, we will proceed with the classification process and build a model to analyze and categorize the text effectively.

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split, RandomizedSearchCV, StratifiedKFold
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [4]:
dataset2 = pd.read_csv("C:/Users/stepm/Documents/DataSets/email_classification/email_spam2.csv")
dataset3 = pd.read_csv("C:/Users/stepm/Documents/DataSets/email_classification/enron_spam_data.csv")
dataset4 = pd.read_csv("C:/Users/stepm/Documents/DataSets/email_classification/spam_dataset.csv")
dataset5 = pd.read_csv("C:/Users/stepm/Documents/DataSets/email_classification/spam-ham dataset.csv")

In [5]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   84 non-null     object
 1   text    84 non-null     object
 2   type    84 non-null     object
dtypes: object(3)
memory usage: 2.1+ KB

In [6]:
dataset2.head()

                                               title                                               text      type
0                          ?? the secrets to SUCCESS  Hi James,\n\nHave you claim your complimentary...      spam
1                    ?? You Earned 500 GCLoot Points  \nalt_text\nCongratulations, you just earned\n...  not spam
2                         ?? Your GitHub launch code  Here's your GitHub launch code, @Mortyj420!\n ...  not spam
3  [The Virtual Reward Center] Re: ** Clarifications  Hello,\n \nThank you for contacting the Virtua...  not spam
4  10-1 MLB Expert Inside, Plus Everything You Ne...  Hey Prachanda Rawal,\n\nToday's newsletter is ...      spam

In [7]:
def process_data(text:str):
    if text.lower() == "spam":
        return 1
    return 0

In [8]:
dataset2["type"] = dataset2["type"].map(process_data)

In [9]:
dataset2.head()

                                               title                                               text  type
0                          ?? the secrets to SUCCESS  Hi James,\n\nHave you claim your complimentary...     1
1                    ?? You Earned 500 GCLoot Points  \nalt_text\nCongratulations, you just earned\n...     0
2                         ?? Your GitHub launch code  Here's your GitHub launch code, @Mortyj420!\n ...     0
3  [The Virtual Reward Center] Re: ** Clarifications  Hello,\n \nThank you for contacting the Virtua...     0
4  10-1 MLB Expert Inside, Plus Everything You Ne...  Hey Prachanda Rawal,\n\nToday's newsletter is ...     1

In [10]:
dataset2.rename(columns={"type":"spam/ham"}, inplace=True)
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     84 non-null     object
 1   text      84 non-null     object
 2   spam/ham  84 non-null     int64
dtypes: int64(1), object(2)
memory usage: 2.1+ KB

In [11]:
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33716 entries, 0 to 33715
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  33716 non-null  int64
 1   Subject     33716 non-null  object
 2   Message     33664 non-null  object
 3   Spam/Ham    33716 non-null  object
 4   Date        33716 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.3+ MB

In [12]:
dataset3.tail()

       Unnamed: 0                    Subject                                            Message Spam/Ham        Date
33711       33711  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...     spam  2005-07-29
33712       33712  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...     spam  2005-07-29
33713       33713  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...     spam  2005-07-30
33714       33714  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...     spam  2005-07-30
33715       33715  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...     spam  2005-07-31

In [13]:
dataset3["Spam/Ham"] = dataset3["Spam/Ham"].map(process_data)

In [14]:
dataset3.tail()

       Unnamed: 0                    Subject                                            Message  Spam/Ham        Date
33711       33711  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...         1  2005-07-29
33712       33712  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...         1  2005-07-29
33713       33713  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...         1  2005-07-30
33714       33714  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...         1  2005-07-30
33715       33715  fw : re ivanhoe e . s . d  fyi , kim .\n- - - - - original message - - - ...         1  2005-07-31

In [15]:
dataset3.head()["Message"]

0                                                  NaN
1    gary , production from the high island larger ...
2               - calpine daily gas nomination 1 . doc
3    fyi - see note below - already done .\nstella\...
4    fyi .\n- - - - - - - - - - - - - - - - - - - -...
Name: Message, dtype: object

In [16]:
dataset3.rename(columns={"Message":"text", "Spam/Ham":"spam/ham"}, inplace=True)
dataset3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33716 entries, 0 to 33715
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  33716 non-null  int64
 1   Subject     33716 non-null  object
 2   text        33664 non-null  object
 3   spam/ham    33716 non-null  int64
 4   Date        33716 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.3+ MB

In [17]:
dataset4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   message_content  1000 non-null   object
 1   is_spam          1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [18]:
dataset4.head()

                                     message_content  is_spam
0  Hello Lonnie,\n\nJust wanted to touch base reg...        0
1  Congratulations, you've won a prize! Call us n...        1
2  You have been pre-approved for a credit card w...        1
3  Limited time offer, act now! Only a few spots ...        1
4  Your loan has been approved! Transfer funds to...        1

In [19]:
dataset4.rename(columns={"message_content":"text", "is_spam":"spam/ham"}, inplace=True)
dataset4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      1000 non-null   object
 1   spam/ham  1000 non-null   int64
dtypes: int64(1), object(1)
memory usage: 15.8+ KB

In [20]:
dataset5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16869 entries, 0 to 16868
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      16869 non-null  object
 1   spam/ham  16869 non-null  object
dtypes: object(2)
memory usage: 263.7+ KB

In [21]:
dataset5.head()

                                                text spam/ham
0  your loan application is waiting wed escapenum...     spam
1  amazing frankfurt symbol http wwwescapenumber ...     spam
2  every feature the original one has , our goods...     spam
3  in the last newsletter weve informed you that...     spam
4  ben edwards wrote i have a perl script that us...      ham

In [22]:
dataset5["spam/ham"] = dataset5["spam/ham"].map(process_data)

In [23]:
dataset5.head()

                                                text  spam/ham
0  your loan application is waiting wed escapenum...         1
1  amazing frankfurt symbol http wwwescapenumber ...         1
2  every feature the original one has , our goods...         1
3  in the last newsletter weve informed you that...         1
4  ben edwards wrote i have a perl script that us...         0

I will take two column from each of the datasets, and combine them all i to one single csv

In [24]:
df = pd.concat([dataset2[["text", "spam/ham"]], dataset3[["text", "spam/ham"]], dataset4, dataset5], axis=0, ignore_index=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51669 entries, 0 to 51668
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   text      51617 non-null  object
 1   spam/ham  51669 non-null  int64
dtypes: int64(1), object(1)
memory usage: 807.5+ KB

In [25]:
df.dropna(inplace=True)

In [26]:
df.head()

                                                text  spam/ham
0  Hi James,\n\nHave you claim your complimentary...         1
1  \nalt_text\nCongratulations, you just earned\n...         0
2  Here's your GitHub launch code, @Mortyj420!\n ...         0
3  Hello,\n \nThank you for contacting the Virtua...         0
4  Hey Prachanda Rawal,\n\nToday's newsletter is ...         1

In [27]:
df.shape

(51617, 2)

In [28]:
df["text"] = df["text"].str.strip().str.lower()

In [29]:
df.drop_duplicates(inplace=True)
df.shape

(29622, 2)

In [30]:
df.to_csv("C:/Users/stepm/Documents/DataSets/email_classification/message_spam_non-spam-dataset.csv")

In [31]:
x = df["text"]
x.head(), x.shape, type(x)

(0    hi james,\n\nhave you claim your complimentary...
 1    alt_text\ncongratulations, you just earned\n50...
 2    here's your github launch code, @mortyj420!\n ...
 3    hello,\n \nthank you for contacting the virtua...
 4    hey prachanda rawal,\n\ntoday's newsletter is ...
 Name: text, dtype: object,
 (29622,),
 pandas.core.series.Series)


---

Lets remove the new line character frm the text, this character are not Identified as stop word in english thus may not be removed

In [32]:
x.tail(1)

51668    do not decline the chance  anatrim  the very...
Name: text, dtype: object

In [33]:
def clean_data(text):
    return text.replace("\n", "")

In [34]:
x.map(clean_data)

0        hi james,have you claim your complimentary gif...
1        alt_textcongratulations, you just earned500you...
2        here's your github launch code, @mortyj420! an...
3        hello, thank you for contacting the virtual re...
4        hey prachanda rawal,today's newsletter is jam-...
                               ...
51663    president bush has commuted the prison sentenc...
51664    http waterduring escapelong pills x escapenumb...
51665    hi . this is the qmail - send program at corre...
51667    chuck cleland wrote why use a loop here at all...
51668    do not decline the chance  anatrim  the very...
Name: text, Length: 29622, dtype: object

In [35]:
y = df["spam/ham"]

Now we can convert the text data into is numeriacal form to initialize the training processes.

In [36]:
vectorizer = CountVectorizer(stop_words="english", ngram_range=(1, 5),lowercase=True)

In [37]:
x = vectorizer.fit_transform(x)

In [38]:
vectorizer.vocabulary_

{'hi': 4566227,
 'james': 5091809,
 'claim': 1792990,
 'complimentary': 2056911,
 'gift': 4263402,
 've': 9761597,
 'compiled': 2040907,
 'special': 8662951,
 'astrology': 1013284,
 'predicts': 7226747,
 'future': 4158975,
 'enabler': 3152851,
 'correct': 2254244,
 'actions': 605946,
 'click': 1819537,
 'copy': 2224565,
 'thank': 9205652,
 'later': 5352372,
 'love': 5702709,
 'heather': 4521070,
 'hi james': 4568629,
 'james claim': 5092274,
 'claim complimentary': 1793331,
 'complimentary gift': 2056964,
 'gift ve': 4264279,
 've compiled': 9762648,
 'compiled special': 2041216,
 'special astrology': 8663226,
 'astrology gift': 1013285,
 'gift predicts': 4264090,
 'predicts future': 7226792,
 'future enabler': 4160517,
 'enabler correct': 3152852,
 'correct actions': 2254306,
 'actions click': 606062,
 'click claim': 1820167,
 'claim copy': 1793440,
 'copy claim': 2225071,
 'claim thank': 1794542,
 'thank later': 9208795,
 'later love': 5354286,
 'love heather': 5703609,
 'hi james claim': 4568630,
 'james claim complimentary': 5092275,
 'claim complimentary gift': 1793332,
 'complimentary gift ve': 2056965,
 'gift ve compiled': 4264280,
 've compiled special': 9762649,
 'compiled special astrology': 2041217,
 'special astrology gift': 8663227,
 'astrology gift predicts': 1013286,
 'gift predicts future': 4264091,
 'predicts future enabler': 7226793,
 'future enabler correct': 4160518,
 'enabler correct actions': 3152853,
 'correct actions click': 2254307,
 'actions click claim': 606063,
 'click claim copy': 1820177,
 'claim copy claim': 1793441,
 'copy claim thank': 2225072,
 'claim thank later': 1794546,
 'thank later love': 9208813,
 'later love heather': 5354290,
 'hi james claim complimentary': 4568631,
 'james claim complimentary gift': 5092276,
 'claim complimentary gift ve': 1793333,
 'complimentary gift ve compiled': 2056966,
 'gift ve compiled special': 4264281,
 've compiled special astrology': 9762650,
 'compiled special astrology gift': 2041218,
 'special astrology gift predicts': 8663228,
 'astrology gift predicts future': 1013287,
 'gift predicts future enabler': 4264092,
 'predicts future enabler correct': 7226794,
 'future enabler correct actions': 4160519,
 'enabler correct actions click': 3152854,
 'correct actions click claim': 2254308,
 'actions click claim copy': 606064,
 'click claim copy claim': 1820178,
 'claim copy claim thank': 1793442,
 'copy claim thank later': 2225073,
 'claim thank later love': 1794547,
 'thank later love heather': 9208814,
 'hi james claim complimentary gift': 4568632,
 'james claim complimentary gift ve': 5092277,
 'claim complimentary gift ve compiled': 1793334,
 'complimentary gift ve compiled special': 2056967,
 'gift ve compiled special astrology': 4264282,
 've compiled special astrology gift': 9762651,
 'compiled special astrology gift predicts': 2041219,
 'special astrology gift predicts future': 8663229,
 'astrology gift predicts future enabler': 1013288,
 'gift predicts future enabler correct': 4264093,
 'predicts future enabler correct actions': 7226795,
 'future enabler correct actions click': 4160520,
 'enabler correct actions click claim': 3152855,
 'correct actions click claim copy': 2254309,
 'actions click claim copy claim': 606065,
 'click claim copy claim thank': 1820179,
 'claim copy claim thank later': 1793443,
 'copy claim thank later love': 2225074,
 'claim thank later love heather': 1794548,
 'alt_text': 786427,
 'congratulations': 2114294,
 'just': 5188010,
 'earned': 2984640,
 '500': 415818,
 'completed': 2047870,
 'following': 4015836,
 'offer': 6562384,
 'view': 9803535,
 'points': 7115641,
 'history': 4598048,
 'stop': 8833953,
 'recieving': 7676008,
 'notifications': 6481637,
 'earn': 2984044,
 'visit': 9829116,
 'profile': 7382495,
 'preferences': 7228723,
 'change': 1687432,
 'setting': 8393215,
 'room': 8047205,
 '1203': 143925,
 '12th': 146597,
 'floor': 3990521,
 'tower': 9399082,
 'china': 1753415,
 'hong': 4628578,
 'kong': 5301315,
 'city': 1787679,
 '33': 354957,
 'canton': 1547305,
 'road': 8022847,
 'tsim': 9518040,
 'sha': 8406706,
 'tsui': 9518475,
 'kowloon': 5303822,
 'unsubscribe': 9627642,
 'alt_text congratulations': 786428,
 'congratulations just': 2114622,
 'just earned': 5192191,
 'earned 500': 2984718,
 '500 completed': 416628,
 'completed following': 2048870,
 'following offer': 4022112,
 'offer view': 6567653,
 'view points': 9805845,
 'points history': 7117090,
 'history stop': 4599670,
 'stop recieving': 8835757,
 'recieving notifications': 7676017,
 'notifications earn': 6481673,
 'earn points': 2984523,
 'points visit': 7118854,
 'visit profile': 9831526,
 'profile click': 7382702,
 'click preferences': 1822863,
 'preferences change': 7228755,
 'change setting': 1693740,
 'setting room': 8394365,
 'room 1203': 8047269,
 '1203 12th': 143926,
 '12th floor': 146598,
 'floor tower': 3992545,
 'tower china': 9399178,
 'china hong': 1754144,
 'hong kong': 4628605,
 'kong city': 5301369,
 'city 33': 1787716,
 '33 canton': 355712,
 'canton road': 1547326,
 'road tsim': 8024109,
 'tsim sha': 9518041,
 'sha tsui': 8406754,
 'tsui kowloon': 9518476,
 'kowloon hong': 5303823,
 'kong unsubscribe': 5301585,
 'alt_text congratulations just': 786429,
 'congratulations just earned': 2114623,
 'just earned 500': 5192192,
 'earned 500 completed': 2984719,
 '500 completed following': 416629,
 'completed following offer': 2048877,
 'following offer view': 4022120,
 'offer view points': 6567654,
 'view points history': 9805846,
 'points history stop': 7117094,
 'history stop recieving': 4599671,
 'stop recieving notifications': 8835758,
 'recieving notifications earn': 7676018,
 'notifications earn points': 6481674,
 'earn points visit': 2984527,
 'points visit profile': 7118855,
 'visit profile click': 9831527,
 'profile click preferences': 7382703,
 'click preferences change': 1822864,
 'preferences change setting': 7228756,
 'change setting room': 1693744,
 'setting room 1203': 8394366,
 'room 1203 12th': 8047270,
 '1203 12th floor': 143927,
 '12th floor tower': 146599,
 'floor tower china': 3992546,
 'tower china hong': 9399179,
 'china hong kong': 1754145,
 'hong kong city': 4628632,
 'kong city 33': 5301370,
 'city 33 canton': 1787717,
 '33 canton road': 355713,
 'canton road tsim': 1547327,
 'road tsim sha': 8024110,
 'tsim sha tsui': 9518042,
 'sha tsui kowloon': 8406755,
 'tsui kowloon hong': 9518477,
 'kowloon hong kong': 5303824,
 'hong kong unsubscribe': 4628780,
 'alt_text congratulations just earned': 786430,
 'congratulations just earned 500': 2114624,
 'just earned 500 completed': 5192193,
 'earned 500 completed following': 2984720,
 '500 completed following offer': 416630,
 'completed following offer view': 2048878,
 'following offer view points': 4022121,
 'offer view points history': 6567655,
 'view points history stop': 9805847,
 'points history stop recieving': 7117095,
 'history stop recieving notifications': 4599672,
 'stop recieving notifications earn': 8835759,
 'recieving notifications earn points': 7676019,
 'notifications earn points visit': 6481675,
 'earn points visit profile': 2984528,
 'points visit profile click': 7118856,
 'visit profile click preferences': 9831528,
 'profile click preferences change': 7382704,
 'click preferences change setting': 1822865,
 'preferences change setting room': 7228757,
 'change setting room 1203': 1693745,
 'setting room 1203 12th': 8394367,
 'room 1203 12th floor': 8047271,
 '1203 12th floor tower': 143928,
 '12th floor tower china': 146600,
 'floor tower china hong': 3992547,
 'tower china hong kong': 9399180,
 'china hong kong city': 1754146,
 'hong kong city 33': 4628633,
 'kong city 33 canton': 5301371,
 'city 33 canton road': 1787718,
 '33 canton road tsim': 355714,
 'canton road tsim sha': 1547328,
 'road tsim sha tsui': 8024111,
 'tsim sha tsui kowloon': 9518043,
 'sha tsui kowloon hong': 8406756,
 'tsui kowloon hong kong': 9518478,
 'kowloon hong kong unsubscribe': 5303827,
 'alt_text congratulations just earned 500': 786431,
 'congratulations just earned 500 completed': 2114625,
 'just earned 500 completed following': 5192194,
 'earned 500 completed following offer': 2984721,
 '500 completed following offer view': 416631,
 'completed following offer view points': 2048879,
 'following offer view points history': 4022122,
 'offer view points history stop': 6567656,
 'view points history stop recieving': 9805848,
 'points history stop recieving notifications': 7117096,
 'history stop recieving notifications earn': 4599673,
 'stop recieving notifications earn points': 8835760,
 'recieving notifications earn points visit': 7676020,
 'notifications earn points visit profile': 6481676,
 'earn points visit profile click': 2984529,
 'points visit profile click preferences': 7118857,
 'visit profile click preferences change': 9831529,
 'profile click preferences change setting': 7382705,
 'click preferences change setting room': 1822866,
 'preferences change setting room 1203': 7228758,
 'change setting room 1203 12th': 1693746,
 'setting room 1203 12th floor': 8394368,
 'room 1203 12th floor tower': 8047272,
 '1203 12th floor tower china': 143929,
 '12th floor tower china hong': 146601,
 'floor tower china hong kong': 3992548,
 'tower china hong kong city': 9399181,
 'china hong kong city 33': 1754147,
 'hong kong city 33 canton': 4628634,
 'kong city 33 canton road': 5301372,
 'city 33 canton road tsim': 1787719,
 '33 canton road tsim sha': 355715,
 'canton road tsim sha tsui': 1547329,
 'road tsim sha tsui kowloon': 8024112,
 'tsim sha tsui kowloon hong': 9518044,
 'sha tsui kowloon hong kong': 8406757,
 'tsui kowloon hong kong unsubscribe': 9518479,
 'github': 4270044,
 'launch': 5361998,
 'code': 1862659,
 'mortyj420': 6213425,
 'octocat': 6558897,
 'standing': 8741305,
 'rocket': 8032930,
 'continue': 2172243,
 'signing': 8498814,
 'entering': 3310018,
 '63024610': 453701,
 'open': 6629483,
 'github launch': 4270049,
 'launch code': 5362166,
 'code mortyj420': 1866959,
 'mortyj420 octocat': 6213426,
 'octocat standing': 6558898,
 'standing rocket': 8741770,
 'rocket continue': 8032955,
 'continue signing': 2176231,
 'signing github': 8499090,
 'github entering': 4270045,
 'entering code': 3310089,
 'code 63024610': 1862775,
 '63024610 open': 453702,
 'open github': 6631543,
 'github launch code': 4270050,
 'launch code mortyj420': 5362167,
 'code mortyj420 octocat': 1866960,
 'mortyj420 octocat standing': 6213427,
 'octocat standing rocket': 6558899,
 'standing rocket continue': 8741771,
 'rocket continue signing': 8032956,
 'continue signing github': 2176232,
 'signing github entering': 8499091,
 'github entering code': 4270046,
 'entering code 63024610': 3310090,
 'code 63024610 open': 1862776,
 '63024610 open github': 453703,
 'github launch code mortyj420': 4270051,
 'launch code mortyj420 octocat': 5362168,
 'code mortyj420 octocat standing': 1866961,
 'mortyj420 octocat standing rocket': 6213428,
 'octocat standing rocket continue': 6558900,
 'standing rocket continue signing': 8741772,
 'rocket continue signing github': 8032957,
 'continue signing github entering': 2176233,
 'signing github entering code': 8499092,
 'github entering code 63024610': 4270047,
 'entering code 63024610 open': 3310091,
 'code 63024610 open github': 1862777,
 'github launch code mortyj420 octocat': 4270052,
 'launch code mortyj420 octocat standing': 5362169,
 'code mortyj420 octocat standing rocket': 1866962,
 'mortyj420 octocat standing rocket continue': 6213429,
 'octocat standing rocket continue signing': 6558901,
 'standing rocket continue signing github': 8741773,
 'rocket continue signing github entering': 8032958,
 'continue signing github entering code': 2176234,
 'signing github entering code 63024610': 8499093,
 'github entering code 63024610 open': 4270048,
 'entering code 63024610 open github': 3310092,
 'hello': 4534510,
 'contacting': 2158697,
 'virtual': 9825355,
 'reward': 7968398,
 'center': 1646046,
 'dictate': 2719198,
 'rewards': 7969039,
 'sent': 8332114,
 'recipients': 7676702,
 'contact': 2150188,
 'program': 7389697,
 'sponsor': 8696109,
 'company': 2001143,
 'originally': 6711124,
 'received': 7661031,
 'helpdesk': 4549776,
 'cspace': 2365497,
 'com': 1894977,
 'inquiry': 4922450,
 'apologize': 875885,
 'inconvenience': 4835254,
 'customer': 2400369,
 'support': 8991587,
 'team': 9111010,
 'lead': 5388434,
 'hello thank': 4537177,
 'thank contacting': 9206839,
 'contacting virtual': 2159166,
 'virtual reward': 9825743,
 'reward center': 7968434,
 'center virtual': 1649900,
 'center dictate': 1647200,
 'dictate rewards': 2719231,
 'rewards sent': 7969248,
 'sent recipients': 8336413,
 'recipients contact': 7676750,
 'contact program': 2155935,
 'program sponsor': 7395520,
 'sponsor company': 8696164,
 'company originally': 2018106,
 'originally received': 6711570,
 'received reward': 7664963,
 'reward helpdesk': 7968571,
 'helpdesk cspace': 4549807,
 'cspace com': 2365498,
 'com inquiry': 1911324,
 'inquiry apologize': 4922483,
 'apologize inconvenience': 876130,
 'inconvenience thank': 4835429,
 'thank virtual': 9211611,
 'center customer': 1647102,
 'customer support': 2403489,
 'support team': 8998351,
 'team lead': 9114758,
 'hello thank contacting': 4537181,
 'thank contacting virtual': 9206840,
 'contacting virtual reward': 2159167,
 'virtual reward center': 9825744,
 'reward center virtual': 7968441,
 'center virtual reward': 1649904,
 'reward center dictate': 7968438,
 'center dictate rewards': 1647201,
 'dictate rewards sent': 2719232,
 'rewards sent recipients': 7969249,
 'sent recipients contact': 8336414,
 'recipients contact program': 7676751,
 'contact program sponsor': 2155936,
 'program sponsor company': 7395521,
 'sponsor company originally': 8696165,
 'company originally received': 2018110,
 'originally received reward': 6711574,
 'received reward helpdesk': 7664964,
 'reward helpdesk cspace': 7968572,
 'helpdesk cspace com': 4549808,
 'cspace com inquiry': 2365499,
 'com inquiry apologize': 1911325,
 'inquiry apologize inconvenience': 4922484,
 'apologize inconvenience thank': 876185,
 'inconvenience thank virtual': 4835435,
 'thank virtual reward': 9211612,
 'reward center customer': 7968435,
 'center customer support': 1647106,
 'customer support team': 2403541,
 'support team lead': 8998392,
 'hello thank contacting virtual': 4537182,
 'thank contacting virtual reward': 9206841,
 'contacting virtual reward center': 2159168,
 'virtual reward center virtual': 9825749,
 'reward center virtual reward': 7968442,
 'center virtual reward center': 1649905,
 'virtual reward center dictate': 9825747,
 'reward center dictate rewards': 7968439,
 'center dictate rewards sent': 1647202,
 'dictate rewards sent recipients': 2719233,
 'rewards sent recipients contact': 7969250,
 'sent recipients contact program': 8336415,
 'recipients contact program sponsor': 7676752,
 'contact program sponsor company': 2155937,
 'program sponsor company originally': 7395522,
 'sponsor company originally received': 8696166,
 'company originally received reward': 2018111,
 'originally received reward helpdesk': 6711575,
 'received reward helpdesk cspace': 7664965,
 'reward helpdesk cspace com': 7968573,
 'helpdesk cspace com inquiry': 4549809,
 'cspace com inquiry apologize': 2365500,
 'com inquiry apologize inconvenience': 1911326,
 'inquiry apologize inconvenience thank': 4922485,
 'apologize inconvenience thank virtual': 876188,
 'inconvenience thank virtual reward': 4835436,
 'thank virtual reward center': 9211613,
 'virtual reward center customer': 9825745,
 'reward center customer support': 7968436,
 'center customer support team': 1647107,
 'customer support team lead': 2403542,
 'hello thank contacting virtual reward': 4537183,
 'thank contacting virtual reward center': 9206842,
 'contacting virtual reward center virtual': 2159169,
 'virtual reward center virtual reward': 9825750,
 'reward center virtual reward center': 7968443,
 'center virtual reward center dictate': 1649906,
 'virtual reward center dictate rewards': 9825748,
 'reward center dictate rewards sent': 7968440,
 'center dictate rewards sent recipients': 1647203,
 'dictate rewards sent recipients contact': 2719234,
 'rewards sent recipients contact program': 7969251,
 'sent recipients contact program sponsor': 8336416,
 'recipients contact program sponsor company': 7676753,
 'contact program sponsor company originally': 2155938,
 'program sponsor company originally received': 7395523,
 'sponsor company originally received reward': 8696167,
 'company originally received reward helpdesk': 2018112,
 'originally received reward helpdesk cspace': 6711576,
 'received reward helpdesk cspace com': 7664966,
 'reward helpdesk cspace com inquiry': 7968574,
 'helpdesk cspace com inquiry apologize': 4549810,
 'cspace com inquiry apologize inconvenience': 2365501,
 'com inquiry apologize inconvenience thank': 1911327,
 'inquiry apologize inconvenience thank virtual': 4922486,
 'apologize inconvenience thank virtual reward': 876189,
 'inconvenience thank virtual reward center': 4835437,
 'thank virtual reward center customer': 9211614,
 'virtual reward center customer support': 9825746,
 'reward center customer support team': 7968437,
 'center customer support team lead': 1647108,
 'hey': 4564345,
 'prachanda': 7214338,
 'rawal': 7605821,
 'today': 9343556,
 'newsletter': 6415564,
 'jam': 5091583,
 'packed': 6765085,
 'need': 6316290,
 'blockbuster': 1302715,
 'day': 2486873,
 'including': 4825398,
 'insider': 4926361,
 'play': 7061986,
 'video': 9799530,
 'picks': 6998485,
 'spotlight': 8701376,
 'games': 4181116,
 'deals': 2536419,
 'way': 9928597,
 'saying': 8193187,
 'thanks': 9212067,
 'strap': 8854945,
 'let': 5437419,
 'great': 4366523,
 'saturday': 8175310,
 '____________________________________________': 529687,
 'expert': 3740757,
 'andre': 831755,
 'ifill': 4759128,
 'strong': 8875634,
 'mlb': 6125971,
 'rolling': 8042663,
 'comes': 1940960,
 'perfect': 6929751,
 'diamond': 2716700,
 '10': 89582,
 '11': 115372,
 'heck': 4524140,
 'run': 8080662,
 'zeroed': 10249258,
 'huge': 4715555,
 'calling': 1520231,
 'sizzler': 8544316,
 'best': 1228548,
 '14': 154416,
 '00': 0,
 'week': 9965522,
 'plays': 7067862,
 '59': 441530,
 'ceasars': 1637390,
 'ready': 7627284,
 'caesar': 1497948,
 'place': 7026628,
 'bet': 1238542,
 'doesn': 2853118,
 'win': 10037659,
 'caesars': 1498020,
 'refund': 7716423,
 '1250': 145401,
 'sweetened': 9033835,
 'pot': 7180199,
 'lose': 5678990,
 '000': 13549,
 'credits': 2343732,
 'tier': 9290456,
 'use': 9657991,
 'promo': 7417927,
 'winnersfull': 10049969,
 'sign': 8488535,
 'disclaimer': 2780547,
 '21': 272248,
 'terms': 9163480,
 'conditions': 2083718,
 'apply': 892946,
 'game': 4178979,
 'braves': 1373433,
 'vs': 9862420,
 'reds': 7698739,
 'boutros': 1356933,
 'atlanta': 1016757,
 'cincinnati': 1779309,
 'jared': 5104366,
 'shuster': 8478594,
 'mound': 6218696,
 'granot': 4358778,
 'spam': 8653621,
 'ashcraft': 967963,
 'expected': 3725163,
 'starting': 8754826,
 'pitcher': 7021614,
 'start': 8746525,
 'went': 9996909,
 'innings': 4917328,
 'gave': 4212583,
 'hits': 4602139,
 'walks': 9875658,
 'struck': 8880513,
 'colorado': 1889756,
 'rockies': 8033264,
 'season': 8254818,
 'record': 7684184,
 '57': 436761,
 'era': 3347349,
 '38': 372207,
 'whip': 10013084,
 '23': 286066,
 '22': 279743,
 'bb': 1175559,
 'ratio': 7602412,
 'starts': 8756998,
 'opposing': 6661247,
 'batters': 1172110,
 'hitting': 4602620,
 '233': 291191,
 'good': 4317424,
 'offense': 6562196,
 'league': 5397647,
 'runs': 8089971,
 'home': 4619487,
 'rbis': 7608213,
 'batting': 1172344,
 'average': 1083512,
 'obp': 6541707,
 'slg': 8556867,
 'ops': 6662508,
 'matt': 5909923,
 'olson': 6613567,
 'leads': 5396616,
 'ronald': 8046105,
 'acuna': 621368,
 'stolen': 8831491,
 'bases': 1162223,
 'finish': 3955546,
 'reading': 7624753,
 'prediction': 7226202,
 'contest': 2168073,
 'predictions': 7226351,

In [39]:
vectorizer.get_feature_names_out()

array(['00', '00 00', '00 00 00', ..., '李俊杰 wrote dear',
       '李俊杰 wrote dear lister', '李俊杰 wrote dear lister friends'],
      shape=(10311909,), dtype=object)

In [40]:
vectorizer.get_stop_words()

frozenset({'a',
           'about',
           'above',
           'across',
           'after',
           'afterwards',
           'again',
           'against',
           'all',
           'almost',
           'alone',
           'along',
           'already',
           'also',
           'although',
           'always',
           'am',
           'among',
           'amongst',
           'amoungst',
           'amount',
           'an',
           'and',
           'another',
           'any',
           'anyhow',
           'anyone',
           'anything',
           'anyway',
           'anywhere',
           'are',
           'around',
           'as',
           'at',
           'back',
           'be',
           'became',
           'because',
           'become',
           'becomes',
           'becoming',
           'been',
           'before',
           'beforehand',
           'behind',
           'being',
           'below',
           'beside',
           'besides',
           'between',
           'beyond',
           'bill',
           'both',
           'bottom',
           'but',
           'by',
           'call',
           'can',
           'cannot',
           'cant',
           'co',
           'con',
           'could',
           'couldnt',
           'cry',
           'de',
           'describe',
           'detail',
           'do',
           'done',
           'down',
           'due',
           'during',
           'each',
           'eg',
           'eight',
           'either',
           'eleven',
           'else',
           'elsewhere',
           'empty',
           'enough',
           'etc',
           'even',
           'ever',
           'every',
           'everyone',
           'everything',
           'everywhere',
           'except',
           'few',
           'fifteen',
           'fifty',
           'fill',
           'find',
           'fire',
           'first',
           'five',
           'for',
           'former',
           'formerly',
           'forty',
           'found',
           'four',
           'from',
           'front',
           'full',
           'further',
           'get',
           'give',
           'go',
           'had',
           'has',
           'hasnt',
           'have',
           'he',
           'hence',
           'her',
           'here',
           'hereafter',
           'hereby',
           'herein',
           'hereupon',
           'hers',
           'herself',
           'him',
           'himself',
           'his',
           'how',
           'however',
           'hundred',
           'i',
           'ie',
           'if',
           'in',
           'inc',
           'indeed',
           'interest',
           'into',
           'is',
           'it',
           'its',
           'itself',
           'keep',
           'last',
           'latter',
           'latterly',
           'least',
           'less',
           'ltd',
           'made',
           'many',
           'may',
           'me',
           'meanwhile',
           'might',
           'mill',
           'mine',
           'more',
           'moreover',
           'most',
           'mostly',
           'move',
           'much',
           'must',
           'my',
           'myself',
           'name',
           'namely',
           'neither',
           'never',
           'nevertheless',
           'next',
           'nine',
           'no',
           'nobody',
           'none',
           'noone',
           'nor',
           'not',
           'nothing',
           'now',
           'nowhere',
           'of',
           'off',
           'often',
           'on',
           'once',
           'one',
           'only',
           'onto',
           'or',
           'other',
           'others',
           'otherwise',
           'our',
           'ours',
           'ourselves',
           'out',
           'over',
           'own',
           'part',
           'per',
           'perhaps',
           'please',
           'put',
           'rather',
           're',
           'same',
           'see',
           'seem',
           'seemed',
           'seeming',
           'seems',
           'serious',
           'several',
           'she',
           'should',
           'show',
           'side',
           'since',
           'sincere',
           'six',
           'sixty',
           'so',
           'some',
           'somehow',
           'someone',
           'something',
           'sometime',
           'sometimes',
           'somewhere',
           'still',
           'such',
           'system',
           'take',
           'ten',
           'than',
           'that',
           'the',
           'their',
           'them',
           'themselves',
           'then',
           'thence',
           'there',
           'thereafter',
           'thereby',
           'therefore',
           'therein',
           'thereupon',
           'these',
           'they',
           'thick',
           'thin',
           'third',
           'this',
           'those',
           'though',
           'three',
           'through',
           'throughout',
           'thru',
           'thus',
           'to',
           'together',
           'too',
           'top',
           'toward',
           'towards',
           'twelve',
           'twenty',
           'two',
           'un',
           'under',
           'until',
           'up',
           'upon',
           'us',
           'very',
           'via',
           'was',
           'we',
           'well',
           'were',
           'what',
           'whatever',
           'when',
           'whence',
           'whenever',
           'where',
           'whereafter',
           'whereas',
           'whereby',
           'wherein',
           'whereupon',
           'wherever',
           'whether',
           'which',
           'while',
           'whither',
           'who',
           'whoever',
           'whole',
           'whom',
           'whose',
           'why',
           'will',
           'with',
           'within',
           'without',
           'would',
           'yet',
           'you',
           'your',
           'yours',
           'yourself',
           'yourselves'})

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [42]:
x_train.shape

(20735, 10311909)

In [43]:
skf = StratifiedKFold(n_splits=100, shuffle=True, random_state=42)

In [44]:
desion_tree = DecisionTreeClassifier(max_depth=250)

In [46]:
desion_tree.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=250)

In [59]:
d_tree_pred_y = desion_tree.predict(x_test)

In [60]:
score = f1_score(y_test, d_tree_pred_y)
score

0.9147864184008763

In [61]:
r_forest = RandomForestClassifier(n_estimators=250, max_depth=200, verbose=2, n_jobs=20)

In [63]:
r_forest.fit(x_train, y_train)

[Parallel(n_jobs=20)]: Using backend ThreadingBackend with 20 concurrent workers.

building tree 1 of 250
building tree 2 of 250
building tree 3 of 250
building tree 4 of 250
building tree 5 of 250
building tree 6 of 250
building tree 7 of 250
building tree 8 of 250
building tree 9 of 250
building tree 10 of 250
building tree 11 of 250
building tree 12 of 250
building tree 13 of 250
building tree 14 of 250
building tree 15 of 250
building tree 16 of 250
building tree 17 of 250
building tree 18 of 250
building tree 19 of 250
building tree 20 of 250
building tree 21 of 250

[Parallel(n_jobs=20)]: Done   1 tasks      | elapsed:   44.6s

building tree 22 of 250
building tree 23 of 250
building tree 24 of 250
building tree 25 of 250
building tree 26 of 250
building tree 27 of 250
building tree 28 of 250
building tree 29 of 250
building tree 30 of 250
building tree 31 of 250
building tree 32 of 250
building tree 33 of 250
building tree 34 of 250
building tree 35 of 250
building tree 36 of 250
building tree 37 of 250
building tree 38 of 250
building tree 39 of 250
building tree 40 of 250
building tree 41 of 250
building tree 42 of 250
building tree 43 of 250
building tree 44 of 250
building tree 45 of 250
building tree 46 of 250
building tree 47 of 250
building tree 48 of 250
building tree 49 of 250
building tree 50 of 250
building tree 51 of 250
building tree 52 of 250
building tree 53 of 250
building tree 54 of 250
building tree 55 of 250
building tree 56 of 250
building tree 57 of 250
building tree 58 of 250
building tree 59 of 250
building tree 60 of 250
building tree 61 of 250
building tree 62 of 250
building tree 63 of 250
building tree 64 of 250
building tree 65 of 250
building tree 66 of 250
building tree 67 of 250
building tree 68 of 250
building tree 69 of 250
building tree 70 of 250
building tree 71 of 250
building tree 72 of 250
building tree 73 of 250
building tree 74 of 250
building tree 75 of 250
building tree 76 of 250
building tree 77 of 250
building tree 78 of 250
building tree 79 of 250
building tree 80 of 250
building tree 81 of 250
building tree 82 of 250
building tree 83 of 250
building tree 84 of 250
building tree 85 of 250
building tree 86 of 250
building tree 87 of 250
building tree 88 of 250
building tree 89 of 250
building tree 90 of 250
building tree 91 of 250
building tree 92 of 250
building tree 93 of 250
building tree 94 of 250
building tree 95 of 250
building tree 96 of 250
building tree 97 of 250
building tree 98 of 250
building tree 99 of 250
building tree 100 of 250
building tree 101 of 250
building tree 102 of 250
building tree 103 of 250
building tree 104 of 250
building tree 105 of 250
building tree 106 of 250
building tree 107 of 250
building tree 108 of 250
building tree 109 of 250
building tree 110 of 250
building tree 111 of 250
building tree 112 of 250
building tree 113 of 250
building tree 114 of 250
building tree 115 of 250
building tree 116 of 250
building tree 117 of 250
building tree 118 of 250
building tree 119 of 250
building tree 120 of 250
building tree 121 of 250
building tree 122 of 250
building tree 123 of 250
building tree 124 of 250
building tree 125 of 250
building tree 126 of 250
building tree 127 of 250
building tree 128 of 250
building tree 129 of 250
building tree 130 of 250
building tree 131 of 250
building tree 132 of 250
building tree 133 of 250
building tree 134 of 250
building tree 135 of 250
building tree 136 of 250
building tree 137 of 250
building tree 138 of 250
building tree 139 of 250
building tree 140 of 250
building tree 141 of 250
building tree 142 of 250

[Parallel(n_jobs=20)]: Done 122 tasks      | elapsed:  6.2min

building tree 143 of 250
building tree 144 of 250
building tree 145 of 250
building tree 146 of 250
building tree 147 of 250
building tree 148 of 250
building tree 149 of 250
building tree 150 of 250
building tree 151 of 250
building tree 152 of 250
building tree 153 of 250
building tree 154 of 250
building tree 155 of 250
building tree 156 of 250
building tree 157 of 250
building tree 158 of 250
building tree 159 of 250
building tree 160 of 250
building tree 161 of 250
building tree 162 of 250
building tree 163 of 250
building tree 164 of 250
building tree 165 of 250
building tree 166 of 250
building tree 167 of 250
building tree 168 of 250
building tree 169 of 250
building tree 170 of 250
building tree 171 of 250
building tree 172 of 250
building tree 173 of 250
building tree 174 of 250
building tree 175 of 250
building tree 176 of 250
building tree 177 of 250
building tree 178 of 250
building tree 179 of 250
building tree 180 of 250
building tree 181 of 250
building tree 182 of 250
building tree 183 of 250
building tree 184 of 250
building tree 185 of 250
building tree 186 of 250
building tree 187 of 250
building tree 188 of 250
building tree 189 of 250
building tree 190 of 250
building tree 191 of 250
building tree 192 of 250
building tree 193 of 250
building tree 194 of 250
building tree 195 of 250
building tree 196 of 250
building tree 197 of 250
building tree 198 of 250
building tree 199 of 250
building tree 200 of 250
building tree 201 of 250
building tree 202 of 250
building tree 203 of 250
building tree 204 of 250
building tree 205 of 250
building tree 206 of 250
building tree 207 of 250
building tree 208 of 250
building tree 209 of 250
building tree 210 of 250
building tree 211 of 250
building tree 212 of 250
building tree 213 of 250
building tree 214 of 250
building tree 215 of 250
building tree 216 of 250
building tree 217 of 250
building tree 218 of 250
building tree 219 of 250
building tree 220 of 250
building tree 221 of 250
building tree 222 of 250
building tree 223 of 250
building tree 224 of 250
building tree 225 of 250
building tree 226 of 250
building tree 227 of 250
building tree 228 of 250
building tree 229 of 250
building tree 230 of 250
building tree 231 of 250
building tree 232 of 250
building tree 233 of 250
building tree 234 of 250
building tree 235 of 250
building tree 236 of 250
building tree 237 of 250
building tree 238 of 250
building tree 239 of 250
building tree 240 of 250
building tree 241 of 250
building tree 242 of 250
building tree 243 of 250
building tree 244 of 250
building tree 245 of 250
building tree 246 of 250
building tree 247 of 250
building tree 248 of 250
building tree 249 of 250
building tree 250 of 250

[Parallel(n_jobs=20)]: Done 250 out of 250 | elapsed: 11.7min finished

RandomForestClassifier(max_depth=200, n_estimators=250, n_jobs=20, verbose=2)

In [65]:
r_tree_pred_y = r_forest.predict(x_test)

[Parallel(n_jobs=20)]: Using backend ThreadingBackend with 20 concurrent workers.
[Parallel(n_jobs=20)]: Done   1 tasks      | elapsed:    0.9s
[Parallel(n_jobs=20)]: Done 122 tasks      | elapsed:    6.8s
[Parallel(n_jobs=20)]: Done 250 out of 250 | elapsed:   13.0s finished

In [66]:
r_score = f1_score(y_test, r_tree_pred_y)

In [67]:
r_score

0.7820236813778256

In [ ]:
In teresting how the decision tree performs better than the random forest, may guess, too many trees dilut